# Generated by Django 4.2.11 on 2026-06-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vk_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk_photo',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
