# Generated by Django 5.2.13 on 2026-04-20 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lost', 'Пропал'), ('found', 'Найден')], max_length=10, verbose_name='Тип')),
                ('animal_type', models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('other', 'Другое')], max_length=10, verbose_name='Вид животного')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
                ('color', models.CharField(max_length=100, verbose_name='Окрас')),
                ('district', models.CharField(choices=[('Центральный', 'Центральный'), ('Северный', 'Северный'), ('Южный', 'Южный'), ('Восточный', 'Восточный'), ('Западный', 'Западный')], max_length=20, verbose_name='Район')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата пропажи/находки')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Опубликовано'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
