# Generated by Django 4.2.11 on 2026-06-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон для связи'),
        ),
    ]
