# Generated by Django 4.2.11 on 2026-06-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/', verbose_name='Фото 2'),
        ),
        migrations.AddField(
            model_name='ad',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='district',
            field=models.CharField(choices=[('Октябрьский', 'Октябрьский'), ('Ленинский', 'Ленинский'), ('Фрунзенский', 'Фрунзенский')], max_length=20, verbose_name='Район'),
        ),
    ]
