# Generated by Django 4.2.11 on 2026-06-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_notification_adview_favorite'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status'], name='ads_ad_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['type'], name='ads_ad_type_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['animal_type'], name='ads_ad_animal_type_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['district'], name='ads_ad_district_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['author'], name='ads_ad_author_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', 'type'], name='ads_ad_status_type_idx'),
        ),
    ]
