# Generated by Django 4.2.11 on 2026-06-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_ads_ad_status_idx_ad_ads_ad_type_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['lat', 'lng'], name='ad_coords_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['created_at'], name='ad_created_idx'),
        ),
    ]
