# Generated by Django 4.2.11 on 2026-06-17 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0006_ad_ad_coords_idx_ad_ad_created_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Опубликовано'), ('rejected', 'Отклонено')], max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Опубликовано'), ('rejected', 'Отклонено')], max_length=20, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ads.ad', verbose_name='Объявление')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'История статуса объявления',
                'verbose_name_plural': 'История статусов объявлений',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['ad'], name='ad_status_hist_ad_idx'), models.Index(fields=['changed_at'], name='ad_status_hist_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_photos/', verbose_name='Фотография')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ads.ad', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Фотография объявления',
                'verbose_name_plural': 'Фотографии объявлений',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('ad', 'sort_order')},
            },
        ),
    ]
